source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PXSDK_Example', :exclusive => true do
  pod "PXSDK", :path => "../"
end

target 'PXSDK_Tests', :exclusive => true do
  pod "PXSDK", :path => "../"

  
end
